services:
  nu-nav:
    image: simonchang/nu-nav:latest
    container_name: nu-nav
    restart: always
    ports:
      - "3000:80"
    volumes:
      # 持久化数据目录
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/dev.db