services:
  nu-nav:
    image: sailong/nu-nav:latest
    container_name: nu-nav
    restart: always
    ports:
      - "80:80"
    volumes:
      # 持久化数据目录
      - ./nu-nav-data:/app/backend/prisma
        environment:
          - DATABASE_URL=file:/app/backend/prisma/dev.db
    