services:
  nu-nav:
    image: simonchang/nu-nav:latest
    container_name: nu-nav
    restart: always
    ports:
      - "80:80"
        volumes:
          # 挂载到独立的数据目录，避免覆盖代码中的 prisma 文件夹
          - ./nu-nav-data:/app/data
        environment:
          - DATABASE_URL=file:/app/data/dev.db
    